# Generated by Django 3.1.6 on 2021-03-27 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20210323_1334'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalproduct',
            name='price_proline',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='product',
            name='link_proline',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='product',
            name='price_proline',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='link_morele',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='link_xkom',
            field=models.URLField(blank=True),
        ),
    ]
