# Generated by Django 3.1.6 on 2021-03-17 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20210315_1154'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalproduct',
            name='category',
        ),
        migrations.RemoveField(
            model_name='historicalproduct',
            name='price',
        ),
        migrations.RemoveField(
            model_name='historicalproduct',
            name='product_name',
        ),
        migrations.RemoveField(
            model_name='product',
            name='price',
        ),
        migrations.AddField(
            model_name='historicalproduct',
            name='price_morele',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='historicalproduct',
            name='price_xkom',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='product',
            name='price_morele',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='product',
            name='price_xkom',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
