# Generated by Django 3.1.6 on 2021-03-17 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20210317_1217'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='link',
            new_name='link_morele',
        ),
        migrations.AddField(
            model_name='historicalproduct',
            name='link_morele',
            field=models.URLField(default='https://www.morele.net/', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historicalproduct',
            name='link_xkom',
            field=models.URLField(default='https://www.x-kom.pl/', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='link_xkom',
            field=models.URLField(default='https://www.x-kom.pl/', max_length=255),
            preserve_default=False,
        ),
    ]
