# Generated by Django 3.1.6 on 2021-03-17 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20210317_1231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalproduct',
            name='link_morele',
            field=models.URLField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='historicalproduct',
            name='link_xkom',
            field=models.URLField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='historicalproduct',
            name='price_morele',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='historicalproduct',
            name='price_xkom',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='link_morele',
            field=models.URLField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='product',
            name='link_xkom',
            field=models.URLField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='product',
            name='price_morele',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='price_xkom',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10),
        ),
    ]
