# Generated by Django 3.1.6 on 2021-03-19 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20210319_1310'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalproduct',
            name='slug',
        ),
    ]
