# Generated by Django 3.1.6 on 2021-03-19 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_remove_historicalproduct_slug'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Watchlist',
        ),
    ]
