# Generated by Django 3.1.6 on 2021-03-22 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_watchlist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='watchlist',
            name='title',
        ),
    ]
