# Generated by Django 3.1.6 on 2021-03-22 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20210322_1255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watchlist',
            name='products',
            field=models.ManyToManyField(blank=True, to='core.Product'),
        ),
    ]
