# Generated by Django 3.1.6 on 2021-03-22 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20210322_1316'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalproduct',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='product',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='product',
            name='updated_at',
        ),
    ]
