# Generated by Django 3.1.6 on 2021-03-22 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_auto_20210322_1541'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalproduct',
            name='link_morele',
        ),
        migrations.RemoveField(
            model_name='historicalproduct',
            name='link_xkom',
        ),
    ]
